# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestEmpressem' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'TTGSnackbar'
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage'
  pod 'UIActivityIndicator-for-SDWebImage' 
  
  # Pods for TestEmpressem

end
